version: '3.8'

services:
  traefik:
    image: traefik
    network_mode: host
    volumes:
      - './traefik.yml:/etc/traefik/traefik.yml'
      - './config.yml:/etc/traefik/config.yml'
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
